export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';
export const START_GET_DATA = 'START_GET_DATA';
export const GET_DATA_SCCUSS = 'GET_DATA_SCCUSS';
export const GET_DATA_ERROR = 'GET_DATA_ERROR';
export const START_GET_SELECTED_PRODUCT = 'START_GET_ONE_PRODUCT';
export const GET_SELECTED_PRODUCT_SUCCESS = 'GET_ONE_PRODUCT_SUCCESS';
export const GET_SELECTED_PRODUCT_ERROR = 'GET_ONE_PRODUCT_ERROR';

export const LOAD_ALL_PRODUCTS = 'LOAD_ALL_PRODUCTS';
export const DISPLAY_PRODUCTS_IN_LIST = 'DISPLAY_PRODUCTS_IN_LIST';
export const DISPLAY_PRODUCTS_IN_GRID = 'DISPLAY_PRODUCTS_IN_GRID';
export const UPDATE_LAST_SORT = 'UPDATE_LAST_SORT';
export const SORT_PRODUCTS = 'SORT_PRODUCTS';
export const UPDATE_FILTER = 'UPDATE_FILTER';
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const CLEAR_FILTER = 'CLEAR_FILTER';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const CLEAR_CART = 'CLEAR_CART';
export const TOGGLE_ITEM_COUNT = 'TOGGLE_ITEM_COUNT';
export const GET_TOTAL_ITEMS = 'GET_TOTAL_ITEMS';









