export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';
export const START_GET_DATA = 'START_GET_DATA';
export const GET_DATA_SCCUSS = 'GET_DATA_SCCUSS';
export const GET_DATA_ERROR = 'GET_DATA_ERROR';
export const START_GET_SELECTED_PRODUCT = 'START_GET_ONE_PRODUCT';
export const GET_SELECTED_PRODUCT_SUCCESS = 'GET_ONE_PRODUCT_SUCCESS';
export const GET_SELECTED_PRODUCT_ERROR = 'GET_ONE_PRODUCT_ERROR';